version: "3"

services:
  postgres:
    container_name: postgresSQL-container
    image: postgres:16.1-alpine3.18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
  
  flask-api:
    container_name: flask-container
    build:
      context: ./flask
    ports:
      - "5000:5000"
    environment:
      - FLASK_PORT=5000
    depends_on:
      - postgres
    restart: always

  bot:
    container_name: bot-container
    build:
      context: ./bot_aio
    environment:
      - FLASK_IP_ADDRESS=flask-api
      - FLASK_PORT=5000
      - BOT_TOKEN=Enter_your_API_key
    depends_on:
      - flask-api
    restart: always
volumes:
  db-data:
